### ISSUE TITLE
Option for setting missing dates only

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-tool_coursedates#1]
I think it's a valid use case to only fill in "missing" (zero) end dates for courses.

**Comment by lucaboesch** [comment]
I'd love to have this, too.
Sometimes lecturers have gone to the settings and already set an enddate themselves.

**Comment by lucaboesch** [comment]
Oh, I see. That's brilliant!
Then I reckon this issue can be closed.
Let me add I've submitted a PR to state this detail in the explaniratory paragraph, see https://github.com/LafColITS/moodle-tool_coursedates/pull/13

Best,
Luca
