### ISSUE TITLE
Course end dates not set correctly if start date is not set

### ISSUE THREAD

**Issue by cborn** [LafColITS/moodle-tool_coursedates#3]
For courses that had not had a Course Start Date set in the DB (because the Edit Settings page for the course had never been visited and saved) this tool will not set the course end date according to the date entered on the tool's page.  Instead a date in 1970 is set.

In this case, the options to enable the Course End Date and disable the Automatic calculation of the end dates are both applied correctly, it's just the date that is wrong.

For courses that have a Course Start Date set, the Course End Date is applied correctly.

**Comment by mackensen** [comment]
This isn't an issue with the plugin. Moodle's internal functions don't consider `0` a valid start date when updating a course. If you change both the start date and the end date it will work correctly.
